carts/urls.py
from django.urls import path
from carts.views import cart_home,cart_update, checkout_home

app_name = 'carts'
urlpatterns = [
    path('',cart_home,name ='home'),
    path('update',cart_update,name = 'update'),
    path('checkout',checkout_home,name = 'checkout')
]

products/urls.py
from django.urls import path
from products.views import  ProductListView, ProductDetailView,ProductFeatureDetailView,ProductFeatureListView,ProductSlugDetailView
from . import views

app_name ='products'

urlpatterns = [
        
    path('product/',ProductListView.as_view(),name = 'product_list'),
    # path('product/<int:pk>/',ProductDetailView.as_view(),name = 'product_detail'),
    path('product/<str:slug>/',ProductSlugDetailView.as_view(),name = 'product_detail'),
    path('featured/',ProductFeatureListView.as_view()),
    path('featured/<int:pk>/',ProductFeatureDetailView.as_view()),
]

search/urls.py
from django.urls import path
from search.views import SearchProductListView
from . import views

app_name ='search'

urlpatterns = [    
    path('',SearchProductListView.as_view(),name = 'query'),
]

superhuman/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include, path
from . import views, settings

from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls',namespace = 'accounts')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('test',views.TestView.as_view(),name='test'),
    path('thank',views.ThanksView.as_view(),name='thank'),
    path('',views.HomeView.as_view(),name = 'home'),  
    path('products/', include('products.urls',namespace = 'products')),
    path('search/', include('search.urls',namespace = 'search')),
    path('carts/', include('carts.urls',namespace = 'carts')),
    path('home',views.HomeView.as_view(),name = 'home')
    
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

search/models.py
from django.db import models

# Create your models here.

search/views.py
from django.shortcuts import render
from products.models import Product
from django.views.generic import ListView
from django.db.models import Q
# Create your views here.

class SearchProductListView(ListView):
    model = Product
    template_name = "search/view.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["query"] = self.request.GET.get('q')
        return context
    
    def get_queryset(self,*args, **kwargs):
        request = self.request
        method_dict = request.GET
        query = method_dict.get('q',None)

        if query is not None:
            loopups = Q( title__icontains = query)|Q(description__icontains = query)|Q(price__icontains = query)|Q(tag__title__icontains = query)
            return Product.objects.filter(loopups).distinct()
        return Product.objects.featured() 
    

search/templates/search/view.html
{% extends 'base.html' %}
  {% block content %}



{% if query%}
<p style='text-align:center;margin-top:20px'>
result for <b> {{query}}</b>
</p>
<hr>
{% else %}
<form methor='GET' action="{%url 'search:query'%}"> 
<input style='margin-left:800px' type='text' placeholder = 'search' name='q' value={{request.GET.q}}>
<button class='btn btn-success' type='submit' style='margin-left:px'>search</button>
</form>
{% endif %}
<div class='container'>
<div class='row'>
{% for obj in object_list %}
<div class='col'>
<div class="card" style="width: 18rem;">
{% if obj.image %}
  <img src="{{obj.image.url}}" class="card-img-top" alt="No image">
{% endif %}
  <div class="card-body">
    <h5 class="card-title">{{forloop.counter}}.{{obj.title}}</h5>
    <p class="card-text">{{obj.description}}</p>
    <a href="{%url 'products:product_detail' obj.slug %}" class="btn btn-primary">View</a>
  </div>
 
</div>
</div>
<hr>
{% endfor %}
</div>
</div>

  
    {% endblock content %}