accounts/urls.py
from django.urls import path
from django.urls import include, path
from django.contrib.auth import views as auth_views
from . import views


app_name = 'accounts'

urlpatterns = [
    path('login/',auth_views.LoginView.as_view(template_name='accounts/login.html'),name = 'login'),
    path('logout/',auth_views.LogoutView.as_view(),name ='logout'),
    path('signup/',views.SignUp.as_view(),name='signup'),
    # path('user',views.userprofile,name='home')
]

carts/urls.py
from django.urls import path
from carts.views import cart_home,cart_update, checkout_home

app_name = 'carts'
urlpatterns = [
    path('',cart_home,name ='home'),
    path('update',cart_update,name = 'update'),
    path('checkout',checkout_home,name = 'checkout')
]

products/urls.py
from django.urls import path
from products.views import  ProductListView, ProductDetailView,ProductFeatureDetailView,ProductFeatureListView,ProductSlugDetailView
from . import views

app_name ='products'

urlpatterns = [
        
    path('product/',ProductListView.as_view(),name = 'product_list'),
    # path('product/<int:pk>/',ProductDetailView.as_view(),name = 'product_detail'),
    path('product/<str:slug>/',ProductSlugDetailView.as_view(),name = 'product_detail'),
    path('featured/',ProductFeatureListView.as_view()),
    path('featured/<int:pk>/',ProductFeatureDetailView.as_view()),
]

search/urls.py
from django.urls import path
from search.views import SearchProductListView
from . import views

app_name ='search'

urlpatterns = [    
    path('',SearchProductListView.as_view(),name = 'query'),
]

superhuman/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include, path
from . import views, settings

from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls',namespace = 'accounts')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('test',views.TestView.as_view(),name='test'),
    path('thank',views.ThanksView.as_view(),name='thank'),
    path('',views.HomeView.as_view(),name = 'home'),  
    path('products/', include('products.urls',namespace = 'products')),
    path('search/', include('search.urls',namespace = 'search')),
    path('carts/', include('carts.urls',namespace = 'carts')),
    path('home',views.HomeView.as_view(),name = 'home')
    
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <!-- Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <!-- Medium Style Editor -->
    <script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/master.css' %}">
    {% comment %} font awsesome {% endcomment %}
   <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet"> 
    <title>SuperHuman</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
  
    <a class="navbar-brand" href="{% url 'home' %}">Super Human</a>
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
 {% if user.is_authenticated %}
          <li class="navbar-light">
                     <a class="nav-link" href="{% url 'products:product_list' %}">Products</a>
                 </li>
                   
                 <li>
                <a class="nav-link" href="{% url 'accounts:logout' %}">Log Out</a>
            </li>
      
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
    <form methor='GET' action="{%url 'search:query'%}" class="form-inline my-2 my-lg-0"> 
<input class="form-control mr-sm-2" type='text' placeholder = 'search' name='q' value={{request.GET.q}}>
<button class='btn btn-success' type='submit'>search</button>
</form>
      {% else %}
      <li><a class="nav-link" href="{% url 'accounts:login' %}">Log In</a></li>
       <li><a class="nav-link" href="{% url 'accounts:signup' %}">Sign Up</a></li>
    </ul>
  </div>
      {% endif %}
      <li><a class="nav-link" href="{% url 'carts:home' %}">{{request.session.cart_total}} <i class="fa fa-shopping-cart" aria-hidden="true"></i>
</a></li>
</nav>
<div class='container'>
    {% block content %}
    
    {% endblock content %}
</div>
    </div>
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% block content %}
<h1>Welcome to superhuman</h1>

{% endblock content %}

templates/test.html
{% extends 'base.html' %}
{% block content %}
<h1>Thank you for logging in to Superhuman</h1>

{% endblock content %}

templates/thank.html
{% extends 'base.html' %}
{% block content %}
<h1>Thanks for coming, Come back soon!</h1>
{% endblock content %}